global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15672"]

  - job_name: "consumer"
    static_configs:
      - targets: ["host.docker.internal:8001"]
